version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-28

    working_directory: ~/plastique

    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-XX:+HeapDumpOnOutOfMemoryError"
      GRADLE_OPTS: "-Dorg.gradle.cache.cleanup=false -Dorg.gradle.jvmargs='-Xmx2048m -XX:MaxMetaspaceSize=320m' -Dkotlin.daemon.jvm.options=-Xmx512m -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

    steps:
      - checkout

      - run:
          name: Update Android SDK
          command: |
            yes | sdkmanager --licenses || true
            yes | sdkmanager --update || true

      - run:
          name: Check Environment
          command: java -version

      - restore_cache:
          keys:
            - v3-plastique-{{ checksum  "build.gradle" }}-{{ checksum "gradle/versions.gradle" }}
            - v3-plastique-

      - run:
          name: Build and Test
          command: ./gradlew testDebug :app:lintProdDebug :app:lintProdRelease :detekt --max-workers=2 --stacktrace
          no_output_timeout: 5m

      - run:
          name: Copy heap dumps
          command: |
            mkdir -p /tmp/heap_dumps
            cp *.hprof /tmp/heap_dumps 2>/dev/null || :
          when: on_fail

      - run:
          name: Copy Kotlin Daemon logs
          command: |
            mkdir -p /tmp/kotlin_daemon_logs
            find $TMPDIR -name "kotlin-daemon.*.log" -exec cp {} /tmp/kotlin_daemon_logs/ \;
          when: on_fail

      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.m2/repository
          key: v3-plastique-{{ checksum  "build.gradle" }}-{{ checksum "gradle/versions.gradle" }}

      - store_artifacts:
          path: build/reports/detekt
          destination: reports/detekt

      - store_artifacts:
          path: app/build/reports
          destination: reports/app

      - store_artifacts:
          path: /tmp/heap_dumps
          destination: heap_dumps

      - store_artifacts:
          path: /tmp/kotlin_daemon_logs
          destination: kotlin_daemon_logs

      - store_test_results:
          path: libraries/core/build/test-results

      - store_test_results:
          path: libraries/core-ui/build/test-results

      - store_test_results:
          path: features/settings/build/test-results

workflows:
  version: 2
  build:
    jobs:
      - build
