complexity:
  ComplexMethod:
    ignoreSingleWhenExpression: true
  LongMethod:
    active: false
  TooManyFunctions:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

exceptions:
  ThrowingExceptionsWithoutMessageOrCause:
    active: true

formatting:
  MaximumLineLength:
    maxLineLength: 160

performance:
  SpreadOperator:
    active: false

potential-bugs:
  ImplicitDefaultLocale:
    active: true

style:
  CollapsibleIfStatements:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ForbiddenComment:
    active: false
  MandatoryBracesIfStatements:
    active: true
  MaxLineLength:
    maxLineLength: 160
  NoTabs:
    active: true
  RedundantExplicitType:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    max: 5
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    max: 4
  TrailingWhitespace:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryLet:
    active: true
  UnusedImports:
    active: true
  UseArrayLiteralsInAnnotations:
    active: true
  UseRequire:
    active: true
  VarCouldBeVal:
    active: true
