name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/modules-2
          key: gradle-modules-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            gradle-modules-

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-wrapper-

      - name: Cache local Maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-local-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            maven-local-

      - name: Build
        run: ./gradlew -w :app:assembleDevDebug :app:assembleDevDebugAndroidTest :app:lintDevDebug testDebug detekt

      - name: Upload detekt reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: detekt-reports
          path: build/reports/detekt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: build/reports/all-tests

      - name: Upload Lint reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: lint-results
          path: app/build/reports
