name: "Validate Gradle Wrapper"

on:
  push:
    paths:
      - "gradle/wrapper/**"
      - "gradlew*"

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
